language: c
compiler: clang
dist: bionic
addons:
  apt:
  apt:
    packages:
      - bison
      - xz-utils
      - wget
env:
  - MATRIX_EVAL="CC=clang && CXX=clang++"
before_script:
  -mkdir downloads
  -mkdir builds
  -cd downloads
  -bash ../scripts/download.sh
  -cd ..
  -cd builds
  -bash ../scripts/extract.sh
script:
  -echo "done"