language: c
compiler: clang
dist: bionic
addons:
  apt:
  apt:
    packages:
      - bison
      - xz-utils
      - wget
      - bash
env:
  - MATRIX_EVAL="CC=clang && CXX=clang++"
before_script:
  - mkdir downloads
  - mkdir builds
  - cd downloads
  - ../scripts/download.sh
  - cd ..
  - cd builds
  - ../scripts/extract.sh
  - cd ..
  - pwd
script:
  - echo "done"